- type: job
  id: LPPSecurityEnginer
  name: job-name-security-enginer
  description: job-description-security-enginer
  playTimeTracker: LPPJobSecurityEnginer
  requirements:
    - !type:DepartmentTimeRequirement
      department: Security
      time: 36000
    - !type:DepartmentTimeRequirement
      department: Engineering
      time: 72000
  startingGear: LPPSecurityEngineerGear
  icon: "LPPJobIconSecurityEnginer"
  supervisors: job-supervisors-hos
  canBeAntag: false
  access:
  - Security
  - Brig
  - Maintenance
  - External
  - Engineering
  special:
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant ]

- type: startingGear
  id: LPPSecurityEngineerGear
  equipment:
    jumpsuit: LPPClothingUniformJumpsuitSecEngineer
    back: LPPClothingBackpackSecurityEngineerFilled
    shoes: LPPClothingShoesBootsJackSecEnginer
    eyes: LPPClothingEyesHudSecEng
    gloves: ClothingHandsGlovesColorYellow
    head: ClothingHeadHatHardhatYellow
    id: LPPSecurityEnginerPDA
    outerClothing: ClothingOuterVestHazard
    ears: LPPClothingHeadsetSecurityEngineer
    belt: LPPClothingMilitaryWebbingSecEng
    socks: LPPClothingUnderSocksNormRed
    underwear: LPPBoxerRed
  underwear: LPPBriefsRed
  breast: LPPBraAltRed
  innerClothingSkirt: LPPClothingUniformJumpSkirtSecEngineer
  satchel: LPPClothingSatchelSecurityEngineerFilled
  duffelbag: LPPClothingBackpackDuffelSecurityEngineerFilled
