- type: job
  id: LPPPrisoner
  name: lpp-job-name-prisoner
  description: lpp-job-description-prisoner
  playTimeTracker: JobLPPPrisoner
  startingGear: LPPPrisonerGear
  icon: "JobIconPrisoner"
  supervisors: job-supervisors-everyone
#  access: # Corvax-MRP
#  - Maintenance

- type: startingGear
  id: LPPPrisonerGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitPrisoner
    shoes: ClothingShoesColorBlack
    id: LPPIDCardPrisoner
  innerClothingSkirt: ClothingUniformJumpskirtPrisoner
